server:
  port: 8083
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.37.187.26:3306/wxrobot
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 10
    fetch-registry: true
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: false
item-service:
  ribbon:
    listOfServers: http://localhost:8087
auth:
   jwt:
     pubKeyPath: D:\\public
     priKeyPath: D:\\private
     user:
       expire: 30
       cookieName: wx_token
       minRefreshInterval: 15
